import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import path from "node:path";
import { copyFile, mkdir } from "node:fs/promises";
import { existsSync, watch } from "node:fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const configuredVaultPluginDir = process.env.MARKDOWNCOMPARE_PLUGIN_DIR;
const defaultVaultPluginDir = process.env.HOME
	? path.join(
			process.env.HOME,
			"Documents",
			"Obsidian Vault",
			".obsidian",
			"plugins",
			"markdown-compare",
		)
	: null;

const vaultPluginDir =
	configuredVaultPluginDir ?? (defaultVaultPluginDir && existsSync(defaultVaultPluginDir) ? defaultVaultPluginDir : null);

async function syncToVaultPluginDir() {
	if (!vaultPluginDir) return;
	await mkdir(vaultPluginDir, { recursive: true });
	await Promise.all([
		copyFile("main.js", path.join(vaultPluginDir, "main.js")),
		copyFile("manifest.json", path.join(vaultPluginDir, "manifest.json")),
		copyFile("styles.css", path.join(vaultPluginDir, "styles.css")),
	]);
}

const syncVaultPlugin = {
	name: "sync-vault-plugin",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;
			try {
				await syncToVaultPluginDir();
			} catch (error) {
				console.warn("[MarkdownCompare] Failed to sync build artifacts:", error);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [syncVaultPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await syncToVaultPluginDir();
	process.exit(0);
} else {
	await syncToVaultPluginDir();

	let syncTimer = null;
	const scheduleSync = () => {
		if (syncTimer) clearTimeout(syncTimer);
		syncTimer = setTimeout(() => void syncToVaultPluginDir(), 50);
	};

	watch("manifest.json", scheduleSync);
	watch("styles.css", scheduleSync);

	await context.watch();
}
